quarkus.application.name=service-track-auth-lambda
quarkus.http.port=8080
quarkus.banner.enabled=true
quarkus.log.level=INFO

quarkus.log.console.format=%d{yyyy-MM-dd HH:mm:ss,SSS} %-5p [%c{2.}] [requestId=%X{requestId}] (%t) %s%e%n


mp.jwt.verify.publickey.location=publicKey.pem
mp.jwt.verify.issuer=service-track-api
smallrye.jwt.sign.key.location=privateKey.pem
servicetrack.jwt.expiracao-segundos=3600

quarkus.smallrye-openapi.enabled=false
quarkus.smallrye-openapi.path=/openapi

quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=${POSTGRES_USER:postgres}
quarkus.datasource.password=${POSTGRES_PASSWORD:postgres}
quarkus.datasource.jdbc.url=jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:servicetrack}

quarkus.hibernate-orm.schema-management.strategy=none