quarkus.application.name=service-track-auth-lambda
quarkus.http.port=8080
quarkus.banner.enabled=true
quarkus.log.level=INFO

quarkus.log.console.format=%d{yyyy-MM-dd HH:mm:ss,SSS} %-5p [%c{2.}] [requestId=%X{requestId}] (%t) %s%e%n


mp.jwt.verify.publickey.location=${MP_JWT_VERIFY_PUBLICKEY_LOCATION:publicKey.pem}
mp.jwt.verify.issuer=service-track-api
servicetrack.jwt.expiracao-segundos=3600

quarkus.smallrye-openapi.enabled=false
quarkus.smallrye-openapi.path=/openapi

quarkus.rest-client.usuarios.url=${ST_USU_BASE_URL:http://localhost:8080}
quarkus.rest-client.usuarios.connect-timeout=1000
quarkus.rest-client.usuarios.read-timeout=2000
